- pipeline.id: nusmedpipe
  path.config: "/usr/share/logstash/pipeline/nusmed*.conf"
  pipeline.workers: 3
- pipeline.id: networkpipe
  path.config: "/usr/share/logstash/pipeline/network*.conf"
  pipeline.workers: 1